create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
create table tb_user (id  bigserial not null, city varchar(255), description TEXT, email varchar(255), function varchar(255), name varchar(255), nivel varchar(255), password varchar(255), photo varchar(255), state varchar(255), url TEXT, primary key (id));
alter table tb_user add constraint UK_4vih17mube9j7cqyjlfbcrk4m unique (email);
