INSERT INTO tb_user (name, email, password,description,url,state,nivel) VALUES ('Anderson Conforto','anderson1@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson2@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','pleno');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson4@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','senior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson5@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','junior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson6@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson7@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson8@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson9@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson10@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson11@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');
INSERT INTO tb_user (name, email, password,description,url,photo,state,nivel) VALUES ('Anderson Conforto','anderson12@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG','apenas um teste de inserção','teste','teste','SP','júnior');

